[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piraffe_common = { path = "../common" }
flatbuffers = "2.0.0"
crossbeam = "0.8.1"