[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
flatbuffers = "2.0.0"
piraffe_common = {path="../common"}
log = "0.4.14"
env_logger = "0.9.0"
